#!/bin/bash

set -e

# this is where APT_PROXY should be configured
if [[ -f ~/.lxd-build.rc ]]; then
    . ~/.lxd-build.rc
fi

if [[ -z "$1" ]]; then
    echo "I need the lxc name!"
    exit 1
fi

NAME=$1

if [[ -z "$2" ]]; then
    SERIES=$(lsb_release -cs)
    echo "Defaulting to $SERIES..."
else
    SERIES="$2"
fi

echo "Launching container $NAME, series $SERIES"
set +e
lxc launch -c security.nesting=true ubuntu-daily:"${SERIES}" "$NAME"
set -e


echo -n "Launched... pausing for networking to come up."
while ! lxc list -c4 --format csv "$NAME" | grep -E "eth.*" ; do
    echo -n '.'
    sleep .1
done
echo 

SSH_KEY_PUBLIC="${SSH_KEY_PUBLIC:-$HOME/.ssh/id_rsa.pub}"

if [[ -n "$APT_PROXY" ]]; then
    lxc exec "$NAME" -- sh -c "echo \"Acquire::http::Proxy \\\"${APT_PROXY}\\\";\" >> /etc/apt/apt.conf"
fi
lxc exec "$NAME" -- sh -c 'echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/force-unsafe-io'
lxc exec "$NAME" -- sh -c 'apt-get update && eatmydata apt-get -y upgrade'
echo "Ingesting public ssh key into container: $SSH_KEY_PUBLIC"
lxc exec "$NAME" -- sh -c 'cat >> /home/ubuntu/.ssh/authorized_keys' < "$SSH_KEY_PUBLIC"
lxc exec "$NAME" -- sh -c 'echo "ubuntu ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/99-no-password-for-ubuntu'

