#!/bin/bash

set -e

# this is where APT_PROXY should be configured
if [[ -f ~/.lxd-build.rc ]]; then
    . ~/.lxd-build.rc
fi

if [[ -z "$1" ]]; then
    echo "I need the lxc name!"
    exit 1
fi

NAME=$1

if [[ -z "$2" ]]; then 
    echo "Defaulting to xenial..."
    SERIES="xenial"
else
    SERIES="$2"
fi

echo "Launching container $NAME, series $SERIES"
lxc launch ubuntu:"${SERIES}" "$NAME"

echo -n "Launched... pausing for networking to come up."
while ! lxc info "$NAME" | grep -q -E "eth.*inet\W"; do
    echo -n '.'
    sleep .1
done
echo 

if [[ -n "$APT_PROXY" ]]; then
    lxc exec "$NAME" -- sh -c "echo \"Acquire::http::Proxy \\\"${APT_PROXY}\\\";\" >> /etc/apt/apt.conf"
fi
lxc exec "$NAME" -- sh -c 'echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/force-unsafe-io'
lxc exec "$NAME" -- sh -c 'apt-get update && eatmydata apt-get -y upgrade'
lxc exec "$NAME" -- sh -c "echo \"$(cat ~/.ssh/id_rsa.pub)\" >> /home/ubuntu/.ssh/authorized_keys"
lxc exec "$NAME" -- sh -c 'echo "ubuntu ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/99-no-password-for-ubuntu'

